### ISSUE TITLE
pokmeon trasnfer

### ISSUE THREAD

**Issue by mich3lam** [FeroxRev/Pokemon-Go-Rocket-API#125]
where do i choose what pokemon to trasnfer and what pokemon to evolve? cant find it in files

**Comment by Martiveen** [comment]
This is in the Logic folder. In logic.cs you see 2 functions that execute this. 
You only have to add them in the while(true) loop.

**Comment by mich3lam** [comment]
@Martiveen well ye, that's where i've been looking at but no idea how and where to add them. :\

**Comment by Martiveen** [comment]
If you cannot find that out by yourself. Then I am not sure if you should by trying this..

The transfer part is easy you have to just add the TransferDuplicatePokemon to line 43. 
For evolving Pokemon it is a bit harder. You have to fetch a list of your Pokemon and select the Pokemon you want to evolve. I'd suggest you not try that since it will probably fail and will result in losing your favorite Pokemon ;)

**Comment by davidmateos94** [comment]
`     await _client.SetServer();
                    await RepeatAction(10, async () => await ExecuteFarmingPokestopsAndPokemons(_client));
                    await TransferDuplicatePokemon();
                    TransferDuplicatePokemon`

Is that the right way?

**Comment by Martiveen** [comment]
If it compiles and runs it is the right way ;)

**Comment by davidmateos94** [comment]
It runs
`                    TransferDuplicatePokemon();
`
But no idea if it works, thanks :P
