### ISSUE TITLE
Detection catch weird

### ISSUE THREAD

**Issue by thorvak** [FeroxRev/Pokemon-Go-Rocket-API#155]
detection is weird i dont have dratigni when i see a dratigni in the same spot. I have many duduo, ratata, krabby ...

**Comment by dreadylein** [comment]
Please try to explain it a bit better, what exactly is the iusse ?

**Comment by pavelmoulisjr** [comment]
My presumption is that using one of the map apps, he saw a Dratini at xlat, ylong. Then he started the bot at those exact coordinates, expecting a Dratini instantly.

If I'm correct, 1st action is moving to a Pokéstop, which might be too far from said Dratini. Not sure, can't open up code rn.


Using "ExecuteCatchAllNearbyPokemons" instead of "ExecuteFarmingPokestopsAndPokemons" should solve said issue, I think.

**Comment by dreadylein** [comment]
Most likely logic related, if you can track it down to an api bug, please reopen a iusse
