### ISSUE TITLE
WPF app to use the library

### ISSUE THREAD

**Issue by FeroxRev** [FeroxRev/Pokemon-Go-Rocket-API#69]
Who would like to pick this feature up?

I'm going to separate the logic properly now, but in the meantime someone can start with this.

It would be nice if we can get #18 included as well

**Comment by ArcticXWolf** [comment]
I would love to contribute to that, but as I have little knowledge on how to design such an application beforehand (OOP-wise), I would restrict my participation to working on any ToDo thats open  and not manage or plan it ^^

**Comment by jshield** [comment]
Should this not go into another project? and also what features does it need?

**Comment by martin-podlubny** [comment]
@michaelowens posted screenshot from such project of his on a different PR.. Looks awesome
https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/53#issuecomment-233970372

**Comment by ArcticXWolf** [comment]
Yeah, it should and I think @FeroxRev meant this. Featurewise everything the console application supports and those things mentioned in #18 #19 #24 #45 #51 #52 #53.

**Comment by martin-podlubny** [comment]
Cuz it's one thing to just run the farming bot.. But it's another to have a pogo toolkit app where you can choose from actions to do nicely. Like listing your pokemon, your inventory, your eggs, using items, batch transferring pokemon (maybe even by hitting checkboxes next to them), batch evolving pokemon etc :)

Saying this because I have had people not interesting in farming, but loving the batch-transfer and batch-evolve :)

**Comment by jshield** [comment]
@FeroxRev with what @michaelowens has done so far is WPF a MUST HAVE? WinForms may stand a better chance on Mono as well IMHO

**Comment by ardaozkal** [comment]
Picking this up.

**Comment by lauw** [comment]
Should keep us updated and keep pushing, so perhaps others can also implement features. I'll try to pick something up later.

**Comment by KyonLeague** [comment]
I could make a clean wpf-GUI design with the usage of mahapps-userinterface. :)

**Comment by AnthonyOSX** [comment]
Began a project here if anyone wants to contribute: https://github.com/AnthonyOSX/GO-Bot

**Comment by KyonLeague** [comment]
RIP @AnthonyOSX the money-maker is here.

**Comment by 0dinson** [comment]
Since I am a noob regarding coding, and don't intend on learning it really (not much time atm), I would much rather spend like 20€ on a bot thats working well with decent features, than doing everything myself. I would love to do that, but im afraid only few people really got the skills to do so and im certainly not one of them.

**Comment by FeroxRev** [comment]
Closing and updating wiki

**Comment by HelloKitty** [comment]
I have Unity3D experience and may give it a shot to render what is going on

I'm going to try converting these .proto files to Protobuf-net classes since afaik Google.Protobuf for C# is not supported on all platforms according to Jon Skeet at https://github.com/google/protobuf/issues/414

We don't need a GUI for a bot though imo. Just would be neat to fully play this on Desktop.

**Comment by FeroxRev** [comment]
What classes are you trying to convert? Which are we missing from the current .proto files?

**Comment by HelloKitty** [comment]
@FeroxRev I meant either change them from ugly .proto defs or use protogen from Marc Gravell to generate the classes for use in Protobuf-net. It's more Unity3D friendly than Google.Protobuf

**Comment by HelloKitty** [comment]
A slack or a discord channel could help make this a reality. A desktop version using your API.

For now I'll try to work with the protoc generated classes and .proto's you've put together. Instead I'll focus on moving to RestSharp (the .Net 3.5 version of HTTPClient kind of) and moving the Async code into Coroutines in Unity. After we get the bot itself running in Unity without rendering then maybe we could start to build an interactive version.

**Comment by FineNerds** [comment]
A discord channel would be really nice. I'm always on it 24/7.

**Comment by fonix232** [comment]
This whole protobuf thing will make it hard to port to other devices and platforms (Pokémon GO Lite version written in Xamarin.Forms, anyone?). I've tried making the API compatible with pretty much the broadest PCL Profile (Profile 259), but alas S2 and VarintBitConverter are not made to target those.

**Comment by FeroxRev** [comment]
VarIntBitConverter is also available in the profobuf lib (as encoder) actually

**Comment by AnthonyOSX** [comment]
Porting to other platforms is hardly a concern as Mac users just need a Windows virtual machine (assuming .NET Core isn't available anytime soon). Better yet spin up a Windows server with a basic REST web API.

**Comment by fonix232** [comment]
@FeroxRev then why was the separate library used? IMHO the KISS method should be followed in the future :)

@AnthonyOSX sure. I was thinking more of Xamarin for iOS and Android - with this API lib, it would be pretty easy to write a Xamarin.Forms app that polls the Niantic servers and show the surrounding pokémon. Or a whole (non-cheating oriented) client to play.

**Comment by FeroxRev** [comment]
@fonix232 Because I needed to confirm the protobuf method was working correctly and then i forgot to revert it

**Comment by fonix232** [comment]
Ah okay. Well right now the only libraries that are not supporting Profile259 are the VarintBitConverter and the S2Geography.

**Comment by Myslik** [comment]
After one hour of putting things together I have something like this. Let me know some feedback.

![2016-07-22](https://cloud.githubusercontent.com/assets/707244/17059734/e6a56c1c-5026-11e6-867b-dcb282817a6a.png)
