### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by NoiseControllers** [FeroxRev/Pokemon-Go-Rocket-API#89]

**Comment by FineNerds** [comment]
You download it. Then you put your info in the App.config. Then you run it.

**Comment by yoloswagzz** [comment]
I don't know everyone else github uploads work for me but this 1 doesn't. I am leaving googlerefreshtoken empty because somebody said to in a thread but that doesn't sound right. Fails to compile due to an error.

**Comment by NoiseControllers** [comment]
no I find any executable

**Comment by FineNerds** [comment]
You cannot find an executable because your login details are "hard coded." You could give someone your account information and have them compile it for you though.

**Comment by NoiseControllers** [comment]
I can spend some tutorial?

**Comment by Novalys** [comment]
@NoiseControllers The project is still in a very early phase, there are no "releases" you can download, doble click and run. If you want to use it now you need to download Visual Studio 2015 (I won't go into the details on how to do that since Google can show you how) then after you have it installed you should be able to open the .sln file that comes with the project, that will open the project for you in Visual Studio. If you want after you complete the above steps message me or comment here.

**Comment by NoiseControllers** [comment]
thanks @Novalys visual studio was the solution 

pokemon server down ;:(
